ye = 'year'
protein_cols = ['upstream', 'downstream']
triplet_index_cols = ['upstream', 'actiontype', 'downstream']
integer_agg_index = 'it'
na_names = ['NULL', 'null', 'Null', 'NA', 'NAN', 'nan']

iden = 'identity'
pm = 'pmid'
ye = 'year'
ai = 'ai'
hi_ai = 'aihi'
ps = 'pos'
up = 'up'
dn = 'dn'
ar = 'ar'
ni = 'new_index'
gu = 'guess'
cexp = 'cdf_exp'
qcexp = 'qcdf_exp'
nw = 'nwaves'
wi = 'waveindex'
cpop = 'cpop'
cden = 'cden'
ct = 'cite_count'
dist = gu